//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2007 Openbravo, S.L.
//    http://sourceforge.net/projects/openbravopos
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

package com.openbravo.pos.reports;

import com.openbravo.data.loader.SerializerWrite;
import com.openbravo.pos.forms.AppView;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.List;
import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.QBFCompareEnum;
import com.openbravo.data.loader.SentenceList;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.DataLogicSales;

public class JParamsUsers extends javax.swing.JPanel implements ReportEditorCreator {

    private SentenceList m_sentusers;
    private ComboBoxValModel m_UsersModel;

    /** Creates new form JParamsUsers */
    public JParamsUsers() {
        initComponents();
    }

    public void init(AppView app) {

        DataLogicSales dlSales = (DataLogicSales) app.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");

        // The Users Model
        m_sentusers = dlSales.getUserList();
        m_UsersModel = new ComboBoxValModel();
    }

    public void activate() throws BasicException {
        List a = m_sentusers.list();
        addFirst(a);
        m_UsersModel = new ComboBoxValModel(a);
        m_UsersModel.setSelectedFirst();
        m_jUser.setModel(m_UsersModel); // refresh model
    }

    public SerializerWrite getSerializerWrite() {
        return new SerializerWriteBasic(new Datas[] {Datas.OBJECT, Datas.STRING});
    }

    public Component getComponent() {
        return this;
    }


    protected void addFirst(List a) {
        // do nothing
    }

    public void addActionListener(ActionListener l) {
        m_jUser.addActionListener(l);
    }

    public void removeActionListener(ActionListener l) {
        m_jUser.removeActionListener(l);
    }

    public Object createValue() throws BasicException {

        return new Object[] {
            m_UsersModel.getSelectedKey() == null ? QBFCompareEnum.COMP_NONE : QBFCompareEnum.COMP_EQUALS,
            m_UsersModel.getSelectedKey()
        };
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        m_jUser = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(AppLocal.getIntString("label.byuser"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 60));
        setLayout(null);
        add(m_jUser);
        m_jUser.setBounds(150, 20, 220, 20);

        jLabel8.setText(AppLocal.getIntString("label.user")); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(20, 20, 110, 14);
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox m_jUser;
    // End of variables declaration

}